# Generated by Django 4.2.21 on 2025-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
