# Generated by Django 4.2.21 on 2025-09-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0005_bloodinventory_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taluk',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Nedumangadu', 'Nedumangadu'), ('Chirayinkeezhu', 'Chirayinkeezhu'), ('Kattakada', 'Kattakada'), ('Neyyattinkara', 'Neyyattinkara'), ('Varkala', 'Varkala'), ('Kollam', 'Kollam'), ('Kunnathur', 'Kunnathur'), ('Karunagappally', 'Karunagappally'), ('Kottarakkara', 'Kottarakkara'), ('Pathanapuram', 'Pathanapuram'), ('Punalur', 'Punalur'), ('Adoor', 'Adoor'), ('Konni', 'Konni'), ('Kozhencherry', 'Kozhencherry'), ('Ranni', 'Ranni'), ('Thiruvalla', 'Thiruvalla'), ('Mallappally', 'Mallappally'), ('Cherthala', 'Cherthala'), ('Ambalappuzha', 'Ambalappuzha'), ('Kuttanad', 'Kuttanad'), ('Karthikappally', 'Karthikappally'), ('Chengannur', 'Chengannur'), ('Mavelikkara', 'Mavelikkara'), ('Changanasserry', 'Changanasserry'), ('Kottayam', 'Kottayam'), ('Vaikom', 'Vaikom'), ('Meenachil', 'Meenachil (Palai)'), ('Kanjirappally', 'Kanjirappally'), ('Devikulam', 'Devikulam'), ('Peermade', 'Peermade'), ('Thodupuzha', 'Thodupuzha'), ('Udumbanchola', 'Udumbanchola'), ('Aluva', 'Aluva'), ('Kanayannur', 'Kanayannur (Eranakulam)'), ('Kochi', 'Kochi (Fort Kochi)'), ('Kothamangalam', 'Kothamangalam'), ('Kunnathunad', 'Kunnathunad (Perumbavoor)'), ('Muvattupuzha', 'Muvattupuzha'), ('North Paravur', 'North Paravur'), ('Thrissur', 'Thrissur'), ('Chavakkad', 'Chavakkad'), ('Kodungallur', 'Kodungallur'), ('Mukundapuram', 'Mukundapuram (Irinjalakuda)'), ('Kunnamkulam', 'Kunnamkulam'), ('Thalapilly', 'Thalapilly (Wadakkancheri)'), ('Palakkad', 'Palakkad'), ('Alathur', 'Alathur'), ('Chittur', 'Chittur'), ('Mannarkkad', 'Mannarkkad'), ('Pattambi', 'Pattambi'), ('Ottappalam', 'Ottappalam'), ('Attappady', 'Attappady (Agali)'), ('Perinthalmanna', 'Perinthalmanna'), ('Nilambur', 'Nilambur'), ('Eranad', 'Eranad (Manjeri)'), ('Kondotty', 'Kondotty'), ('Tirur', 'Tirur'), ('Tirurangadi', 'Tirurangadi'), ('Ponnani', 'Ponnani'), ('Kozhikode', 'Kozhikode'), ('Koyilandy', 'Koyilandy'), ('Vadakara', 'Vadakara'), ('Thamarassery', 'Thamarassery'), ('Mananthavady', 'Mananthavady'), ('Vythiri', 'Vythiri (Kalpetta)'), ('Sulthan Bathery', 'Sulthan Bathery'), ('Kannur', 'Kannur'), ('Thalassery', 'Thalassery'), ('Taliparamba', 'Taliparamba'), ('Iritty', 'Iritty'), ('Payyanur', 'Payyanur'), ('Kasaragod', 'Kasaragod'), ('Hosdurg', 'Hosdurg')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='', max_length=50),
        ),
    ]
